DROP POLICY IF EXISTS tenant_active_restrictive ON public.attendance;
CREATE POLICY tenant_active_restrictive ON public.attendance AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.calendar_events;
CREATE POLICY tenant_active_restrictive ON public.calendar_events AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.chat_channel_members;
CREATE POLICY tenant_active_restrictive ON public.chat_channel_members AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.chat_channels;
CREATE POLICY tenant_active_restrictive ON public.chat_channels AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.chat_messages;
CREATE POLICY tenant_active_restrictive ON public.chat_messages AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.employees;
CREATE POLICY tenant_active_restrictive ON public.employees AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.holidays;
CREATE POLICY tenant_active_restrictive ON public.holidays AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.hr_policies;
CREATE POLICY tenant_active_restrictive ON public.hr_policies AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.leaves;
CREATE POLICY tenant_active_restrictive ON public.leaves AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.notifications;
CREATE POLICY tenant_active_restrictive ON public.notifications AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.task_submissions;
CREATE POLICY tenant_active_restrictive ON public.task_submissions AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.tasks;
CREATE POLICY tenant_active_restrictive ON public.tasks AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
DROP POLICY IF EXISTS tenant_active_restrictive ON public.tenant_settings;
CREATE POLICY tenant_active_restrictive ON public.tenant_settings AS RESTRICTIVE FOR ALL TO public USING ((SELECT public.can_access_tenant(tenant_id))) WITH CHECK ((SELECT public.can_access_tenant(tenant_id)));
